### ISSUE TITLE
Enhancement request: sensible filenames

### ISSUE THREAD

**Issue by kseistrup** [traviskaufman/YATI#1]
Please use sensible configuration paths, e.g.:

``` sh
~/.config/yati/
~/.config/yati/yati.rc
~/.config/yati/tweets
```

or similar.

Currently the filenames are only remotely associated with yati, and is spread in the root of the homedir.  Unless one is the author, one has to look up the filenames in the source code in order to find them…

**Comment by traviskaufman** [comment]
Hey sorry I've been off the radar for a bit. I'll be addressing this along with your other two issues this week. Thank you so much for the feedback!

**Comment by traviskaufman** [comment]
Fixed [here](https://github.com/traviskaufman/YATI/commit/3c02d06baefdb391687bbe2de6a09cea816d3188)

**Comment by traviskaufman** [comment]
This will be in the 1.0.1 release

**Comment by kseistrup** [comment]
Great, thanks! :)
